# Generated by Django 4.0.10 on 2023-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='goodreads_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
