# Generated by Django 4.0.10 on 2024-08-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_uploaded',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='book',
            name='scrape_status',
            field=models.BooleanField(default=False),
        ),
    ]
