# Generated by Django 4.0.10 on 2023-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='goodreads_id',
            field=models.CharField(max_length=200),
        ),
    ]
