# Generated by Django 4.0.10 on 2023-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_goodreads_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='original_publication_year',
            field=models.IntegerField(null=True),
        ),
    ]
