# Generated by Django 4.0.10 on 2023-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
