# Generated by Django 4.2.27 on 2026-04-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_birth_place_author_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
