# Generated by Django 4.2.27 on 2026-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
