# Generated by Django 4.0.10 on 2023-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_original_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('goodreads_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(null=True)),
                ('death_date', models.DateTimeField(null=True)),
                ('genres', models.TextField(null=True)),
                ('influences', models.TextField(null=True)),
                ('avg_rating', models.FloatField(null=True)),
                ('reviews_count', models.IntegerField(null=True)),
                ('rating_count', models.IntegerField(null=True)),
                ('about', models.TextField(null=True)),
            ],
        ),
    ]
