# Generated by Django 4.0.10 on 2024-02-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_awards_book_image_url_book_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_updated',
            new_name='last_uploaded',
        ),
    ]
