# Generated by Django 4.0.10 on 2024-01-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='my_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='isbn13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
