# Generated by Django 4.0.10 on 2023-08-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description_book_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='goodreads_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
