# Generated by Django 4.0.10 on 2023-11-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='goodreads_id',
            new_name='author_id',
        ),
    ]
