# Generated by Django 4.0.10 on 2024-11-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_usertag_booktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.review')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.usertag')),
            ],
        ),
        migrations.DeleteModel(
            name='BookTag',
        ),
    ]
