# Generated by Django 4.2.27 on 2026-04-29 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geodata', '0001_initial'),
        ('books', '0004_author_author_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredCountryCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('country', 'user')},
            },
        ),
    ]
