# Generated by Django 4.0.10 on 2023-12-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_goodreads_id_author_author_id'),
    ]
    sql = """create or replace view owned_books_view as 
	select bb.title, br.author, bb.rating_counts, bb.review_counts, bb.description, bb.genres,
	bb.number_of_pages, bb.publish_date, bb.publisher, br.original_publication_year, bb."characters", bb.places
	from books_book bb , books_author ba, books_review br 
	where bb.goodreads_id = br.goodreads_id and br.author = ba."name";"""

    operations = [
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name='OwnedBooksView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('rating_counts', models.IntegerField(blank=True, null=True)),
                ('review_counts', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('original_publication_year', models.IntegerField(blank=True, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
                ('places', models.TextField(null=True)),
            ],
            options={
                'db_table': 'owned_books_view',
                'managed': False,
            },
        ),
    ]
