# Generated by Django 4.0.10 on 2023-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_id_alter_book_goodreads_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreads_id', models.BigIntegerField()),
                ('rating', models.IntegerField()),
                ('date_read', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(null=True)),
                ('bookshelves', models.CharField(max_length=200)),
                ('review', models.TextField(null=True)),
                ('private_notes', models.TextField(null=True)),
                ('read_count', models.IntegerField()),
                ('owned_copies', models.IntegerField()),
            ],
        ),
    ]
