# Generated by Django 4.2.17 on 2024-12-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_quotes_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='scraped_quotes',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
