# Generated by Django 4.0.10 on 2024-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='awards',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
