# Generated by Django 4.0.10 on 2024-01-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_my_rating_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
    ]
