# Generated by Django 4.0.10 on 2024-02-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='awards',
        ),
    ]
