# Generated by Django 4.0.10 on 2023-11-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
