# Generated by Django 4.2.17 on 2025-01-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_scraped_quotes_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.AddField(
            model_name='quote',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuoteQuoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.quote')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.quotetag')),
            ],
        ),
    ]
