# Generated by Django 4.0.10 on 2024-01-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_review_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='review',
            name='isbn13',
        ),
    ]
