# Generated by Django 4.2.17 on 2025-01-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_quotetag_remove_quote_tags_quote_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotequotetag',
            name='quote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotequotetags', to='books.quote'),
        ),
    ]
