# Generated by Django 4.0.10 on 2024-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='category',
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
