# Generated by Django 4.0.10 on 2024-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isbn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
