# Generated by Django 4.0.10 on 2024-02-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_award_category_alter_award_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
