# Generated by Django 4.0.10 on 2024-01-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_review_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isbn13',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
