# Generated by Django 4.0.10 on 2024-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_award_category_alter_award_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
