# Generated by Django 4.2.17 on 2025-10-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_review_unique_user_book_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_text',
        ),
    ]
