# Generated by Django 4.0.10 on 2024-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_review_isbn13'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='year_published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
