# Generated by Django 4.0.10 on 2024-01-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_review_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
    ]
