# Generated by Django 4.2.17 on 2025-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
