# Generated by Django 4.0.10 on 2024-01-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_review_date_added_alter_review_date_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='review',
            name='isbn13',
        ),
    ]
