# Generated by Django 4.0.10 on 2024-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_review_isbn_remove_review_isbn13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='goodreads_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
