# Generated by Django 4.2.17 on 2025-10-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_author_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='book',
        ),
        migrations.AddField(
            model_name='quote',
            name='review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.review'),
            preserve_default=False,
        ),
    ]
