# Generated by Django 4.0.10 on 2024-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_review_goodreads_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='goodreads_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
