# Generated by Django 4.0.10 on 2024-02-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_bookgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreads_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.location')),
            ],
        ),
    ]
