# Generated by Django 4.2.17 on 2025-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_quote_book_quote_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='scraped_quotes',
        ),
        migrations.AddField(
            model_name='review',
            name='scraped_quotes',
            field=models.BooleanField(default=False),
        ),
    ]
