# Generated by Django 4.0.10 on 2024-01-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_id_alter_book_goodreads_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='goodreads_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
