# Generated by Django 4.0.10 on 2024-02-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_location_code_location_latitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
