# Generated by Django 4.0.10 on 2024-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_location_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
