# Generated by Django 4.0.10 on 2024-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_author_birth_date_alter_author_death_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
