# Generated by Django 4.0.10 on 2024-02-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_author_processed_ner_authorner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnedBooksView',
        ),
    ]
