# Generated by Django 4.0.10 on 2024-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_authorlocation_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorlocation',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
