# Generated by Django 4.0.10 on 2024-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_authorlocation_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorlocation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='authorlocation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
