# Generated by Django 4.0.10 on 2024-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_award_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
