# Generated by Django 4.0.10 on 2024-04-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_book_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_content',
        ),
    ]
