# Generated by Django 4.0.10 on 2024-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_rename_review_review_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='isbn13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
