# Generated by Django 4.0.10 on 2024-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_review_isbn_review_isbn13'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_local_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
