# Generated by Django 4.2.17 on 2025-10-04 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='active',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.theme'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
