# Generated by Django 4.2.17 on 2025-10-04 11:59

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_theme_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_theme',
            field=models.ForeignKey(blank=True, default=accounts.models.get_default_theme, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.theme'),
        ),
    ]
