# Generated by Django 4.2.17 on 2025-10-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userpreferences_preferred_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='gallery_cover_size',
            field=models.IntegerField(default=150),
        ),
    ]
