# Generated by Django 4.2.27 on 2026-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userpreferences_gallery_cover_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='week_start',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
