# Generated by Django 4.2.27 on 2026-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userpreferences_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='quotes_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=10),
        ),
    ]
