# Generated by Django 4.2.27 on 2026-04-08 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userpreferences_quotes_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodreadsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cache_file', models.CharField(blank=True, max_length=512)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetch_error', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'unique_together': {('user', 'feed_url')},
            },
        ),
    ]
