# Generated by Django 4.2.27 on 2026-04-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_goodreadsfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=500)),
                ('book_id', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('book_title', models.CharField(blank=True, max_length=500)),
                ('book_author', models.CharField(blank=True, max_length=255)),
                ('book_description', models.TextField(blank=True)),
                ('book_published', models.CharField(blank=True, max_length=20)),
                ('num_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('book_image_url', models.URLField(blank=True, max_length=500)),
                ('book_medium_image_url', models.URLField(blank=True, max_length=500)),
                ('book_large_image_url', models.URLField(blank=True, max_length=500)),
                ('book_image_local', models.CharField(blank=True, max_length=512)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_review', models.TextField(blank=True)),
                ('user_shelves', models.CharField(blank=True, max_length=500)),
                ('user_read_at', models.DateTimeField(blank=True, null=True)),
                ('user_date_added', models.DateTimeField(blank=True, null=True)),
                ('book_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='accounts.goodreadsfeed')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('feed', 'guid')},
            },
        ),
    ]
