# Generated by Django 4.0.10 on 2024-02-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
    ]
