# Generated by Django 4.0.10 on 2024-02-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_rename_name_city_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('combined_name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
