# Generated by Django 4.0.10 on 2024-02-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_ascii',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
