# Generated by Django 4.0.10 on 2024-02-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0007_alter_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
