# Generated by Django 4.0.10 on 2024-02-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_alter_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
