# Generated by Django 4.0.10 on 2024-03-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0009_alter_place_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-population'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['country', 'region_name']},
        ),
    ]
