# Generated by Django 4.0.10 on 2024-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('goodreads_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('author', models.TextField(max_length=300)),
                ('rating_counts', models.IntegerField(blank=True, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('places', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
