# Generated by Django 4.0.10 on 2024-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recs', '0003_booklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-rating_counts']},
        ),
        migrations.AddField(
            model_name='book',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
